import { describe, expect, it } from "vitest";

import {
  calculateProgress,
  createDiffHash,
  createReviewTargetId,
  detectGeneratedFile,
  resolveReviewStates,
  type FileDiff,
  type ReviewMark,
  type ReviewTarget
} from "../src/index.js";

const workingTreeTarget = {
  headRefName: "main",
  headSha: "1111111111111111111111111111111111111111",
  kind: "working_tree",
  projectId: "project-a"
} satisfies ReviewTarget;

const branchTarget = {
  baseRefName: "origin/main",
  baseSha: "2222222222222222222222222222222222222222",
  headRefName: "feature/review",
  headSha: "3333333333333333333333333333333333333333",
  kind: "branch",
  mergeBaseSha: "4444444444444444444444444444444444444444",
  projectId: "project-a"
} satisfies ReviewTarget;

const textDiff = {
  content: {
    kind: "text",
    patch: "@@ -1 +1 @@\n-old\n+new\n"
  },
  newPath: "src/example.ts",
  status: "modified"
} satisfies FileDiff;

describe("review target identity", () => {
  it("creates stable ids for equivalent review targets", () => {
    expect(createReviewTargetId(workingTreeTarget)).toBe(
      createReviewTargetId({ ...workingTreeTarget })
    );
  });

  it("includes branch base and merge-base identity", () => {
    expect(createReviewTargetId(branchTarget)).not.toBe(
      createReviewTargetId({
        ...branchTarget,
        mergeBaseSha: "5555555555555555555555555555555555555555"
      })
    );
  });
});

describe("diff hashes", () => {
  it("are stable for the same file diff", () => {
    expect(createDiffHash(workingTreeTarget, textDiff)).toBe(
      createDiffHash(workingTreeTarget, { ...textDiff })
    );
  });

  it("change when the textual patch changes", () => {
    expect(createDiffHash(workingTreeTarget, textDiff)).not.toBe(
      createDiffHash(workingTreeTarget, {
        ...textDiff,
        content: { kind: "text", patch: "@@ -1 +1 @@\n-old\n+newer\n" }
      })
    );
  });

  it("normalizes CRLF textual patches to LF", () => {
    expect(createDiffHash(workingTreeTarget, textDiff)).toBe(
      createDiffHash(workingTreeTarget, {
        ...textDiff,
        content: { kind: "text", patch: "@@ -1 +1 @@\r\n-old\r\n+new\r\n" }
      })
    );
  });

  it("does not include context snapshot text in review identity", () => {
    expect(createDiffHash(workingTreeTarget, textDiff)).toBe(
      createDiffHash(workingTreeTarget, {
        ...textDiff,
        content: {
          kind: "text",
          newText: "new\nunchanged helper\n",
          oldText: "old\nunchanged helper\n",
          patch: textDiff.content.patch
        }
      })
    );
  });

  it("is scoped to the review target", () => {
    expect(createDiffHash(workingTreeTarget, textDiff)).not.toBe(
      createDiffHash(branchTarget, textDiff)
    );
  });

  it("includes paths and rename metadata", () => {
    expect(createDiffHash(workingTreeTarget, textDiff)).not.toBe(
      createDiffHash(workingTreeTarget, {
        ...textDiff,
        newPath: "src/renamed.ts",
        oldPath: "src/example.ts",
        status: "renamed"
      })
    );
  });

  it("fingerprints binary content by size and digest", () => {
    const binaryDiff = {
      content: {
        byteSize: 4,
        digest: "binary-content-sha",
        kind: "binary"
      },
      newPath: "assets/logo.png",
      status: "modified"
    } satisfies FileDiff;

    expect(createDiffHash(workingTreeTarget, binaryDiff)).not.toBe(
      createDiffHash(workingTreeTarget, {
        ...binaryDiff,
        content: { ...binaryDiff.content, digest: "other-binary-content-sha" }
      })
    );
  });

  it("fingerprints symlink, submodule, and mode-only changes explicitly", () => {
    const symlinkHash = createDiffHash(workingTreeTarget, {
      content: {
        kind: "symlink",
        newTarget: "../new-target",
        oldTarget: "../old-target"
      },
      newPath: "linked",
      status: "modified"
    });
    const submoduleHash = createDiffHash(workingTreeTarget, {
      content: { kind: "submodule", newCommit: "bbb", oldCommit: "aaa" },
      newPath: "vendor/module",
      status: "modified"
    });
    const modeHash = createDiffHash(workingTreeTarget, {
      content: { kind: "mode_only" },
      newMode: "100755",
      newPath: "script.sh",
      oldMode: "100644",
      status: "mode_changed"
    });

    expect(new Set([symlinkHash, submoduleHash, modeHash]).size).toBe(3);
  });
});

describe("generated file detection", () => {
  it("detects high-confidence generated headers and paths", () => {
    expect(
      detectGeneratedFile({
        path: "Sources/Generated/user.pb.swift",
        sample: "// Code generated by protoc. DO NOT EDIT.\n"
      }).isGenerated
    ).toBe(true);
  });

  it("does not classify lockfiles as generated", () => {
    expect(detectGeneratedFile({ path: "pnpm-lock.yaml" }).isGenerated).toBe(false);
    expect(detectGeneratedFile({ path: "package-lock.json" }).isGenerated).toBe(false);
  });

  it("uses text snapshot headers when resolving generated-file visibility", () => {
    const states = resolveReviewStates({
      diffs: [
        {
          content: {
            kind: "text",
            newText: "// Code generated by schema compiler. DO NOT EDIT.\nexport {}\n",
            patch:
              "@@ -0,0 +1,2 @@\n+// Code generated by schema compiler. DO NOT EDIT.\n+export {}\n"
          },
          newPath: "src/schema.ts",
          status: "added"
        }
      ],
      marks: [],
      reviewTarget: workingTreeTarget
    });

    expect(states[0]).toEqual(
      expect.objectContaining({
        generated: true,
        visible: false
      })
    );
  });
});

describe("review state and progress", () => {
  const generatedDiff = {
    content: { kind: "text", patch: "+ generated\n" },
    generated: true,
    newPath: "src/generated/schema.pb.swift",
    status: "added"
  } satisfies FileDiff;

  const currentDiffs = [textDiff, generatedDiff] as const;

  it("marks files reviewed only when target and hash match", () => {
    const targetId = createReviewTargetId(workingTreeTarget);
    const reviewedDiffHash = createDiffHash(workingTreeTarget, textDiff);
    const marks = [
      {
        path: textDiff.newPath,
        reviewedDiffHash,
        reviewTargetId: targetId
      }
    ] satisfies readonly ReviewMark[];

    const states = resolveReviewStates({
      diffs: currentDiffs,
      marks,
      reviewTarget: workingTreeTarget
    });

    expect(states).toEqual([
      expect.objectContaining({ path: textDiff.newPath, reviewed: true }),
      expect.objectContaining({ path: generatedDiff.newPath, reviewed: false })
    ]);
  });

  it("invalidates review when the current hash changes", () => {
    const targetId = createReviewTargetId(workingTreeTarget);
    const staleHash = createDiffHash(workingTreeTarget, textDiff);
    const changedDiff = {
      ...textDiff,
      content: { kind: "text", patch: "+ changed after review\n" }
    } satisfies FileDiff;

    const states = resolveReviewStates({
      diffs: [changedDiff],
      marks: [
        {
          path: changedDiff.newPath,
          reviewedDiffHash: staleHash,
          reviewTargetId: targetId
        }
      ],
      reviewTarget: workingTreeTarget
    });

    expect(states[0]).toEqual(
      expect.objectContaining({ invalidated: true, reviewed: false })
    );
  });

  it("excludes hidden generated files from progress by default", () => {
    const states = resolveReviewStates({
      diffs: currentDiffs,
      marks: [
        {
          path: textDiff.newPath,
          reviewedDiffHash: createDiffHash(workingTreeTarget, textDiff),
          reviewTargetId: createReviewTargetId(workingTreeTarget)
        }
      ],
      reviewTarget: workingTreeTarget
    });

    expect(calculateProgress(states)).toEqual({
      reviewedVisibleFiles: 1,
      totalVisibleReviewableFiles: 1
    });
  });

  it("counts generated files when they are visible", () => {
    const states = resolveReviewStates({
      diffs: currentDiffs,
      marks: [],
      reviewTarget: workingTreeTarget,
      showGeneratedFiles: true
    });

    expect(calculateProgress(states)).toEqual({
      reviewedVisibleFiles: 0,
      totalVisibleReviewableFiles: 2
    });
  });
});
